# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170806_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashpw',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
